# Generated by Django 5.2 on 2025-05-08 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_attributes', '0001_initial_attributes'),
        ('apps_categories', '0001_initial_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=255)),
                ('goods_description', models.TextField(blank=True, null=True)),
                ('goods_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('goods_quantity', models.PositiveIntegerField()),
                ('goods_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('goods_state', models.IntegerField(choices=[(0, 'Non-Confirmed'), (1, 'Pending'), (2, 'Confirmed')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hot_quantity', models.PositiveIntegerField(default=0)),
                ('is_promote', models.BooleanField(default=False)),
                ('goods_big_logo', models.CharField(blank=True, max_length=255, null=True)),
                ('goods_small_logo', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(related_name='products', to='apps_categories.category')),
            ],
            options={
                'db_table': 'apps_products_product',
            },
        ),
        migrations.CreateModel(
            name='ProductPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pics_big', models.CharField(max_length=255)),
                ('pics_mid', models.CharField(max_length=255)),
                ('pics_sma', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pics', to='apps_products.product')),
            ],
            options={
                'db_table': 'apps_products_productpicture',
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr_value', models.CharField(max_length=255)),
                ('attr_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_attributes.categoryattribute')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_products.product')),
            ],
            options={
                'db_table': 'apps_products_productattribute',
                'unique_together': {('product', 'attribute', 'attr_value')},
            },
        ),
    ]
