# Generated by Django 5.2 on 2025-04-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='level',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', to='users.permission'),
        ),
    ]
