# Generated by Django 5.2 on 2025-04-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_permission_level_alter_role_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
