# Generated by Django 5.2 on 2025-05-01 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_permission_level'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='users_userprofile',
        ),
    ]
