# Generated by Django 5.2 on 2025-05-04 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_users', '0001_initial_users'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='apps_users_userprofile',
        ),
    ]
