# Generated by Django 5.2 on 2025-05-05 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_categories', '0001_initial_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr_name', models.CharField(max_length=255)),
                ('attr_sel', models.CharField(choices=[('only', 'Only'), ('many', 'Many')], max_length=10)),
                ('attr_write', models.CharField(choices=[('manual', 'Manual'), ('list', 'List')], max_length=10)),
                ('attr_vals', models.TextField(blank=True, null=True)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='apps_categories.category')),
            ],
            options={
                'verbose_name': 'Category Attribute',
                'verbose_name_plural': 'Category Attributes',
                'db_table': 'apps_attributes_categoryattribute',
                'unique_together': {('cat_id', 'attr_name')},
            },
        ),
    ]
